apiVersion: v1
kind: ReplicationController
metadata:
  namespace: budget-service-dev
  name: wildfly-replication-controller
  labels:
    name: wildfly
    context: BudgetServer
spec:
  replicas: 1
  selector:
    name: wildfly
    context: BudgetServer
  template:
    metadata:
      labels:
        name: wildfly
        context: BudgetServer
    spec:
      containers:
        - name: wildfly
          image: jboss/wildfly:10.1.0.Final
          ports:
            - name: wildfly-port
              containerPort: 8080
              protocol: TCP
            - name: admin-port
              containerPort: 9990
              protocol: TCP
          command: [
                    "sh",
                    "-c",
                    "/opt/jboss/wildfly/bin/standalone.sh -c standalone-ha.xml  -b `hostname --ip-address`"
            ]
          imagePullPolicy: Always
