apiVersion: v1
kind: Service
metadata: 
  name: wildfly-service
  namespace: budget-service-dev
  labels:
    name: wildfly-service
    context: BudgetServer
spec: 
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 8080
      name: http
      targetPort: 8080
      nodePort: 30080
    - port: 9990
      name: management
      targetPort: 9990
      nodePort: 30990
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: wildfly
    context: BudgetServer