---
- hosts: vagrant
  sudo: yes
  roles:
    - { role: base }
    - { role: java8 }
    - { role: wildfly }
    - { role: postgresql }
    - { role: postgresql_instance, db_name: 'budget',  db_user: 'budget' }
  tasks:
    - name: copy the jboss cli scripts to the deployment directory
      copy: src="{{ item }}" dest=~
      with_items:
        - budget-ds.cli
    
    - name: install the ds
      shell: chdir=~ {{ wildfly_prog_directory }}/jboss-cli.sh --file="{{ item }}"
      with_items:
        - budget-ds.cli
