TRUNCATE TABLE workspace CASCADE;
TRUNCATE TABLE account CASCADE;
TRUNCATE TABLE transaction CASCADE;
TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE roles CASCADE;
TRUNCATE TABLE signingkey CASCADE;
TRUNCATE TABLE user_role CASCADE;
